name: Build webpage

on:
  schedule:
    - cron: "0 23 * * * "
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_webpage:
    name: Build webpage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          architecture: x64
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run builder
        run: |
          python src/dump.py
          python src/build.py
        env:
          GITHUB_TOKEN: ${{ secrets.HARUPY_GITHUB_TOKEN }}
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: dist
